### ISSUE TITLE
NoClassDefFoundError: gg.drak.thebase.lib.hikari.HikariConfig on Paper 1.21.10

### ISSUE THREAD

**Issue by hujcuh** [Streamline-Essentials/StreamlineCore#50]
Hello,

After updating StreamlineCore to 2.5.5.7, the plugin fails to initialize its database.

Environment:
- Paper 1.21.10 build 129
- Java 23
- Windows 11
- StreamlineCore 2.5.5.7

Startup error:

java.lang.NoClassDefFoundError:
gg/drak/thebase/lib/hikari/HikariConfig

at singularity.database.DBOperator.buildDataSource(DBOperator.java:78)

Caused by:

java.lang.ClassNotFoundException:
gg.drak.thebase.lib.hikari.HikariConfig

After this error, the main database remains null and causes further exceptions such as:

Cannot invoke
"singularity.database.CoreDBOperator.loadPlayer(String)"
because Singularity.getMainDatabase() is null

and

Cannot invoke
"singularity.database.CoreDBOperator.savePlayer(...)"
because CosmicPlayer.getDatabase() is null
